// src/pages/admin/lib/reportUtils.js
import jsPDF from 'jspdf';

/**
 * Generate a PDF report from data
 * @param {Object} params - Report parameters
 * @param {string} params.type - Report type identifier
 * @param {string} params.title - Report title
 * @param {Array} params.rows - Data rows to include
 * @param {Array} params.columns - Column definitions [{key, label, width?}]
 * @param {Object} params.meta - Metadata {dateFrom, dateTo, generatedBy}
 */
export async function generatePDFReport({ type, title, rows = [], columns = [], meta = {} }) {
  try {
    const pdf = new jsPDF();
    let yPos = 20;
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);

    // Header
    pdf.setFontSize(18);
    pdf.setTextColor(16, 185, 129); // emerald-600
    pdf.text('Zennest Admin Report', margin, yPos);
    yPos += 10;

    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    pdf.text(`Report: ${title}`, margin, yPos);
    yPos += 7;

    // Metadata
    if (meta.dateFrom || meta.dateTo) {
      const dateRange = [
        meta.dateFrom ? new Date(meta.dateFrom).toLocaleDateString() : 'All time',
        meta.dateTo ? new Date(meta.dateTo).toLocaleDateString() : 'Present'
      ].join(' - ');
      pdf.text(`Date Range: ${dateRange}`, margin, yPos);
      yPos += 7;
    }

    pdf.text(`Generated: ${new Date().toLocaleString()}`, margin, yPos);
    yPos += 7;

    if (meta.generatedBy) {
      pdf.text(`Generated by: ${meta.generatedBy}`, margin, yPos);
      yPos += 7;
    }

    yPos += 5;

    // Table header
    if (columns.length > 0 && rows.length > 0) {
      pdf.setFontSize(10);
      pdf.setFont(undefined, 'bold');
      
      // Calculate column widths
      const totalWidth = columns.reduce((sum, col) => sum + (col.width || 1), 0);
      const colWidths = columns.map(col => ((col.width || 1) / totalWidth) * contentWidth);

      // Draw header row
      let xPos = margin;
      columns.forEach((col, idx) => {
        pdf.rect(xPos, yPos - 5, colWidths[idx], 8);
        pdf.text(col.label || col.key, xPos + 2, yPos);
        xPos += colWidths[idx];
      });
      yPos += 10;

      // Draw data rows
      pdf.setFont(undefined, 'normal');
      rows.forEach((row, rowIdx) => {
        // Check if we need a new page
        if (yPos > 280) {
          pdf.addPage();
          yPos = 20;
        }

        xPos = margin;
        columns.forEach((col, colIdx) => {
          const value = row[col.key] ?? '';
          const displayValue = typeof value === 'object' && value !== null
            ? JSON.stringify(value)
            : String(value);
          
          // Truncate long text
          const maxWidth = colWidths[colIdx] - 4;
          const truncated = pdf.splitTextToSize(displayValue, maxWidth);
          
          pdf.text(truncated[0] || '', xPos + 2, yPos);
          xPos += colWidths[colIdx];
        });
        yPos += 7;
      });
    } else {
      pdf.setFontSize(12);
      pdf.text('No data available', margin, yPos);
    }

    // Footer on each page
    const totalPages = pdf.internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(128, 128, 128);
      pdf.text(
        `Page ${i} of ${totalPages} - Zennest Admin Report`,
        pageWidth / 2,
        pdf.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
    }

    // Generate filename
    const slugify = (str) => str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const filename = `${slugify(title)}-${Date.now()}.pdf`;

    pdf.save(filename);
    return { success: true, filename };
  } catch (error) {
    console.error('Error generating PDF report:', error);
    throw error;
  }
}

/**
 * Print a report using HTML
 * @param {Object} params - Print parameters
 * @param {string} params.title - Report title
 * @param {string} params.htmlContent - HTML content to print
 */
export function printReport({ title, htmlContent }) {
  try {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      throw new Error('Popup blocked. Please allow popups for this site.');
    }

    const printHTML = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${title} - Zennest Admin Report</title>
          <style>
            @media print {
              @page {
                margin: 1cm;
              }
            }
            body {
              font-family: Arial, sans-serif;
              padding: 20px;
              color: #1f2937;
            }
            .header {
              border-bottom: 3px solid #10b981;
              padding-bottom: 15px;
              margin-bottom: 20px;
            }
            h1 {
              color: #10b981;
              margin: 0 0 10px 0;
              font-size: 24px;
            }
            .meta {
              color: #6b7280;
              font-size: 12px;
              margin: 5px 0;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 20px;
            }
            th, td {
              border: 1px solid #d1d5db;
              padding: 10px;
              text-align: left;
            }
            th {
              background-color: #10b981;
              color: white;
              font-weight: bold;
            }
            tr:nth-child(even) {
              background-color: #f9fafb;
            }
            .footer {
              margin-top: 30px;
              padding-top: 15px;
              border-top: 1px solid #e5e7eb;
              color: #6b7280;
              font-size: 11px;
              text-align: center;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Zennest Admin Report</h1>
            <div class="meta">
              <div>Report: ${title}</div>
              <div>Generated: ${new Date().toLocaleString()}</div>
            </div>
          </div>
          ${htmlContent}
          <div class="footer">
            <p>Generated by Zennest Admin Dashboard</p>
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(printHTML);
    printWindow.document.close();
    
    // Wait for content to load, then print
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
      }, 250);
    };

    return { success: true };
  } catch (error) {
    console.error('Error printing report:', error);
    throw error;
  }
}

/**
 * Generate contract PDF
 * @param {Object} params - Contract parameters
 * @param {string} params.template - Contract template text
 * @param {Object} params.data - Contract data (hostName, guestName, etc.)
 */
export function generateContractPDF({ template = '', data = {} }) {
  try {
    const pdf = new jsPDF();
    let yPos = 20;
    const margin = 20;
    const pageWidth = pdf.internal.pageSize.getWidth();
    const contentWidth = pageWidth - (margin * 2);

    // Header
    pdf.setFontSize(18);
    pdf.setTextColor(16, 185, 129);
    pdf.text('Zennest Booking Contract', margin, yPos);
    yPos += 15;

    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    pdf.text(`Contract Date: ${new Date().toLocaleDateString()}`, margin, yPos);
    yPos += 15;

    // Replace placeholders in template
    let contractText = template;
    Object.keys(data).forEach(key => {
      const regex = new RegExp(`\\{${key}\\}`, 'g');
      contractText = contractText.replace(regex, data[key] || '');
    });

    // Split template into lines and add to PDF
    if (contractText) {
      const lines = contractText.split('\n');
      pdf.setFontSize(10);
      
      lines.forEach(line => {
        if (yPos > 280) {
          pdf.addPage();
          yPos = 20;
        }
        
        // Handle long lines by splitting them
        const maxWidth = contentWidth - 4;
        const textLines = pdf.splitTextToSize(line || '', maxWidth);
        textLines.forEach(textLine => {
          if (yPos > 280) {
            pdf.addPage();
            yPos = 20;
          }
          pdf.text(textLine, margin, yPos);
          yPos += 7;
        });
      });
    } else {
      pdf.text('Contract terms and conditions...', margin, yPos);
    }

    const filename = `zennest-contract-${Date.now()}.pdf`;
    pdf.save(filename);
    return { success: true, filename };
  } catch (error) {
    console.error('Error generating contract PDF:', error);
    throw error;
  }
}

